### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#21]

**Comment by CyrusSUEN** [comment]
Added: https://github.com/dhowe/AdNauseam2/pull/26 and verfied on Opera, Chrome and Firefox

**Comment by CyrusSUEN** [comment]
I think it's time to apply https://crowdin.com/ for ADN2

**Comment by dhowe** [comment]
@mushon please weigh in on this -- you were against proceeding with internationalization in version 1

**Comment by mushon** [comment]
@dhowe I'm not against doing localization if we're building from the ground up. Especially if this is already supported by the uBlock base.

**Comment by dhowe** [comment]
We are doing a test case with Chinese, then we can look at the strings

**Comment by CyrusSUEN** [comment]
Replacing "uBlock₀" with "AdNauseam" in messages.json (https://github.com/dhowe/AdNauseam2/commit/2fafb3d99c9269d6bbdc8ef4b3201f0623eb0589) is problematic because we will have to update every locale file each time uBlock has locale update.

Update locale handling regarding this issue: https://github.com/dhowe/AdNauseam2/pull/35

After the PR we will just have to update the newly added ADN specific strings.
Or even better if we could separate our changes from uBlock's messages.json file (with another ADN specific messages.json file).

**Comment by dhowe** [comment]
Discuss with me
