### ISSUE TITLE
Confirm dialogs should come from AdNauseam (not extension-id)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#38]
Should read: "AdNauseam says"...

![screen shot 2016-02-27 at 12 19 01 pm](https://cloud.githubusercontent.com/assets/737638/13370750/635f07fc-dd4c-11e5-988c-b266413db15b.png)

**Comment by CyrusSUEN** [comment]
Got fixed by Google in Chrome canary version Version 51.0.2667.0
The Chrome stable version 49.0.2623.75 m still has the problem.
Once the Chrome stable version (and Opera) gets updated, it will be solved.
![1](https://cloud.githubusercontent.com/assets/2461812/13547536/92676992-e312-11e5-9d64-3addf2b42984.PNG)

Now we only need to fix it on Firefox:
![2](https://cloud.githubusercontent.com/assets/2461812/13547537/a198f8f4-e312-11e5-92eb-7a9e712f4fdd.PNG)

**Comment by dhowe** [comment]
You have a plan for this?

**Comment by CyrusSUEN** [comment]
> You have a plan for this?

Yes and I'm working on it

**Comment by CyrusSUEN** [comment]
Fixed: https://github.com/dhowe/AdNauseam2/pull/51

![screen shot 2016-03-06 at 2 18 50 am](https://cloud.githubusercontent.com/assets/2461812/13549528/ead27c78-e341-11e5-9ade-a6f2fb13a294.png)

**Comment by dhowe** [comment]
Nice

**Comment by CyrusSUEN** [comment]
> We should discuss changes like this in the future, and make sure as well that they are implemented correctly for ALL platforms.
Yes. And I've verified that on Chrome, Firefox and Opera before creating the PR.

vAPI.confirm() is a must in this case. The other way I can think of is to use "vAPI.firefox = true" but that's not so elegant.

**Comment by dhowe** [comment]
Need to recheck this once Chrome is updated...

**Comment by CyrusSUEN** [comment]
Chrome dev 50 already has it
Tested on version 50.0.2661.18 dev-m (64-bit).

Will test it later on stable version.

**Comment by CyrusSUEN** [comment]
Fix verfied on Google Chrome stable Version 50.0.2661.75 m (64-bit).
Closing this one.
